name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.2
          - 8.3
          - 8.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Unit Tests
        run: composer test
